### ISSUE TITLE
cannot import galgebra modules

### ISSUE THREAD

**Issue by foobarz** [brombo/galgebra#1]
I get this error:

File "/home/devel/src/galgebra/galgebra-master/galgebra/lt.py", line 264
    raise ValueError('Lt inverse currently implemented only for spinor!\n'))
                                                                           ^
SyntaxError: invalid syntax

I run anaconda, current updated version with Python 2. This error is with the just-rewrote galgebra upload the other day. The galgebra.{mv,metric} import okay.

Looks like there is an extra ')' closing paren causing the syntax error.

**Comment by brombo** [comment]
On 05/19/2015 10:35 PM, foobarz wrote:
>
> I get this error:
>
> File "/home/devel/src/galgebra/galgebra-master/galgebra/lt.py", line 264
> raise ValueError('Lt inverse currently implemented only for spinor!\n'))
> ^
> SyntaxError: invalid syntax
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/1>.
>
Will get fix to github today.

**Comment by foobarz** [comment]
importing is working now, so closing this
