### ISSUE TITLE
'module' object has no attribute 'Ga'

### ISSUE THREAD

**Issue by utensil** [brombo/galgebra#12]
## Enviroment

* MacBook Pro (Retina, 13-inch, Mid 2014)
* OSX 10.11.2
* Python 2.7.11
* numpy 1.9.2
* sympy 1.0

## Steps

```
git clone https://github.com/brombo/galgebra.git
cd galgebra
python setup.py install
python setup.py test
```

```python
import galgebra
galgebra.Ga
```

## Error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Ga'
```

If I `import ga` instead, got

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ga
```

I looked into examples and tests, and can't figure out what went wrong.

**Comment by brombo** [comment]
"python setup.py test" not implemented (I don't really know hot to write 
a setup.py file).  You would need to run tests and examples manually 
(one at a time).  Also "test_test.py" uses old GA format and was not 
converted when I left sympy distribution.  There is no more module MV to 
import. Will fix
test_test.py when I get time.  In examples Terminal/terminal_check.py 
and LaTeX/latex_check.py run same tests and more without asserts 
(answers printed out).

**Comment by utensil** [comment]
Oh it's not about the tests. I saw 0 tests were run.
Just that I can't use any classes in "ga" or "galgebra" after importing any of them in REPL.

**Comment by utensil** [comment]
Let's use exact code from "Terminal/terminal_check.py":

```python
$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from ga import Ga, one, zero
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ga
>>> from galgebra import Ga, one, zero
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Ga
```

**Comment by brombo** [comment]
To install use the instructions starting on page 5 of galgebra.pdf in 
the doc directory (specifically section 1.3 in the doc) not setup.py.  
Note that the Ipython notebook install section is dated.

**Comment by utensil** [comment]
I followed the instructions in galgebra.pdf, still no luck:

```bash
galgebra $ pwd
/Users/utensil/experiments/galgebra/galgebra
galgebra $ ls
__init__.py	__init__.pyc	ga.py		lt.py		metric.py	mv.py		printer.py	setgapth.py
galgebra $ python setgapth.py
Traceback (most recent call last):
  File "setgapth.py", line 28, in <module>
    pth_file = open(pth_name,'w')
IOError: [Errno 2] No such file or directory: '/Users/utensil/miniconda2/lib/site-python/Ga.pth'
galgebra $ ls /Users/utensil/miniconda2/lib/site-python/
ls: /Users/utensil/miniconda2/lib/site-python/: No such file or directory
galgebra $ ls /Users/utensil/miniconda2/lib/
Tk.icns					libQtScript.4.dylib			libmkl_avx2.dylib
Tk.tiff					libQtScript.dylib			libmkl_avx512.dylib
engines					libQtScript.la				libmkl_core.dylib
libQtCLucene.4.8.7.dylib		libQtScript.prl				libmkl_intel.dylib
```

**Comment by utensil** [comment]
After manually created the directory:

```bash
mkdir '/Users/utensil/miniconda2/lib/site-python'
galgebra $ python setgapth.py
os name: posix
site-packages directory: /Users/utensil/miniconda2/lib/site-python/Ga.pth
Ga.pth:
#Path of Ga module
/Users/utensil/experiments/galgebra/galgebra
0

Python pth file Ga.pth for all modules of galgebra has been created and
placed in directory appropriate for Linux, Windows, or OSX.  Note that
if Ga.pth already exists the old version will be deleted.
```

```python
>>> import ga
>>> ga.Ga
<class 'ga.Ga'>
```

Succeed.

**Comment by utensil** [comment]
I'll send a PR to correct instructions in INSTALL .

**Comment by brombo** [comment]
Thanks for your feedback.  I think on OSX the directory where the python 
path files reside is not created when python is installed.  Are you 
using the default python that come with OSX or are your using another 
distribution, if so what distribution?

**Comment by utensil** [comment]
I'm using [MiniConda](http://conda.pydata.org/miniconda.html) which is a minimal distribution of [Anaconda](https://www.continuum.io/why-anaconda) which is widely used.

**Comment by utensil** [comment]
PR sent.

**Comment by utensil** [comment]
Though not related to this issue, I did notice something wrong in `terminal_check`:

```python
print '-I*(grad^A) =', -o3d.E() * (grad ^ A)
```

It should be `.I()` if I'm understanding it correctly.

**Comment by utensil** [comment]
> "python setup.py test" not implemented (I don't really know hot to write
> a setup.py file).  You would need to run tests and examples manually
> (one at a time).  Also "test_test.py" uses old GA format and was not
> converted when I left sympy distribution.  There is no more module MV to
> import. Will fix
> test_test.py when I get time.

I'm interested in writing a `setup.py` for `galgebra`, and add other essential parts to get `galgebra` into [PyPI](http://pypi.python.org/pypi/) so it can be installed with `pip install galgebra`. Also I do have some time to fix the issues you mentioned above. Would you like it to be done? Because I think `galgebra` is a great library.

**Comment by brombo** [comment]
I would greatly appreciate you doing such a thing.  Thank you very much.

**Comment by utensil** [comment]
Great, then I would get started.
