### ISSUE TITLE
Make `galgebra` pip-installable

### ISSUE THREAD

**Issue by utensil** [brombo/galgebra#14]
- [x] write a `setup.py` so it can be installed by `python setup.py install`
- [x] add `.gitignore` and remove `.pyc` files
- [x] add option `--noconflict` to use `galgebra` as namespace
- [x] fix tests
- [ ] [register `galgebra` on PyPI](https://pythonhosted.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg)

This issue is opened to track the work discussed in https://github.com/brombo/galgebra/issues/12#issuecomment-217629670 

The work would be done according to the instructions in the following documents:
- https://docs.python.org/2/install/index.html#inst-config-files
- https://pythonhosted.org/an_example_pypi_project/setuptools.html

**Comment by utensil** [comment]
Work would begin at https://github.com/utensil-contrib/galgebra/tree/14-pip . A PR would be created when 1-3 tasks have been completed.

**Comment by utensil** [comment]
A minimal `setup.py` is written as in commit https://github.com/utensil-contrib/galgebra/commit/2d6606eaec5056dce125b404ebffaa2ef4202ce8 .

But it introduced a problem, these module names would be exposed in the global(just the same as the old Ga.pth approach). Should we put them into the namespace `galgebra`?

**Comment by brombo** [comment]
On 05/08/2016 08:26 AM, Utensil Song wrote:
>
> A minimal |setup.py| is written as in commit utensil-contrib@2d6606e 
> <https://github.com/utensil-contrib/galgebra/commit/2d6606eaec5056dce125b404ebffaa2ef4202ce8> 
> .
>
> But it introduced a problem, these module names would be exposed in 
> the global(just the same as the old Ga.pth approach). Should we put 
> them into the namespace |galgebra|?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/14#issuecomment-217714210>
>
You are afraid that there is some other python library that could expose 
the same module names globally?  The only one I would be worried about 
is "printer."  Could we have an user option to do it either way since 
everyone now using galgebra is doing it with ga.pth?

**Comment by utensil** [comment]
> Could we have an user option to do it either way since
> everyone now using galgebra is doing it with ga.pth?

Yes, we could, `setup.cfg` was exactly for that. After I implemented it, users can write:

```
[global]
noconflict=1
```

in  `setup.cfg`, or use `python setup.py install --noconflict`.

And in the `setup.py`, we could just use this option to choose from `package_dir={'galgebra':'galgebra'},` and `package_dir={'':'galgebra'}`.

**Comment by brombo** [comment]
On 05/08/2016 09:35 AM, Utensil Song wrote:
>
>     Could we have an user option to do it either way since
>     everyone now using galgebra is doing it with ga.pth?
>
> Yes, we could, |setup.cfg| was exactly for that. After I implemented 
> it, users can write:
>
> |[global] noconflict=1 |
>
> in |setup.cfg|, or use |python setup.py install --noconflict|.
>
> And in the |setup.py|, we could just use this option to choose from 
> |package_dir={'galgebra':'galgebra'},| and |package_dir={'':'galgebra'}|.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/14#issuecomment-217718942>
>
Let's do it that way then.

**Comment by utensil** [comment]
Implemented in https://github.com/utensil-contrib/galgebra/commit/7ec591e8138fb2a90a6d59008757385052fb4b0d

**Comment by brombo** [comment]
On 05/08/2016 12:35 PM, Utensil Song wrote:
>
> Implemented in utensil-contrib@7ec591e 
> <https://github.com/utensil-contrib/galgebra/commit/7ec591e8138fb2a90a6d59008757385052fb4b0d>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/14#issuecomment-217731363>
>
I see you are at Texas Tech.  I tracked gcwenken to Texas Tech and 
Chaowen Guo is that who you are?  I live in Silver Spring Maryland. If 
you ever wish to talk in real time my phone number is 301-625-5951.  My 
main interest in GA is for physics.  If you want the GA notes I wrote 
(based on Doran and Lasenby's book) I will put them on Google drive.  We 
have a study group of physicists, mathematician, and astronomers (most 
are retired) that meets on most Friday evenings at the Montgomery 
College planetarium.  We also have two participants that attend remotely 
via Teamviewer.  We are currently covering Lagrangian field theory.  If 
you are interested let me know.

**Comment by utensil** [comment]
Oh, I'm not at Texas Tech. I'm a senior software engineer at [Tencent](http://www.tencent.com/en-us/) in China, mainly focused on back-end server development for online payment, using C++/Java/Python/Node.js. So my work is not related to GA in any way, Physics and GA are my personal interest.

I'm a reader of "Geometric Algebra for Physicists", and came across your work when looking for previous efforts on combining symbolic programming and GA. My main interest in GA is also for physics. To me, GA is a brand new way to look at the math we used in Physics, with the power of simplicity, the ability to connect/unite different areas or aspects, and the potential to further reveal the nature of physics.

Personally, I'm using spare time to digest what I've learned from the book and related materials, and planning to implement a GA library in [Julia](http://julialang.org/)(a very expressive and effective language) as a better way to learn it.

Sorry, due to time zone reason, I might not be able to attend the study group meetings, but I'll really benefit from and appreciate your notes. And I'm also reading [your book](http://www2.montgomerycollege.edu/departments/planet/planet/Numerical_Relativity/bookGA.pdf). It's really very nice of you to share all these.

I haven't been able to find too much progress of GA, especially the applications in Physics. It seems that computer graphics did show some interest in GA, for a possibly more effective way to do rotations than quaternions, and there are some papers to introduce GA to their specific areas in Physics, but not much fruit yet. Do you have a better list of papers regarding this? In other words, do you have a clear roadmap of the latest development of GA? It looks like that, GA is still at a stage to reinterpret established Physics, am I missing something?

**Comment by utensil** [comment]
The last paragraph of my last comment may seem a little doubtful about GA. Actually, I was trying to neutralize my more enthusiastic and radical view: The current math used in physics is not only inefficient but also wrong. By "wrong", I mean that the inefficiency of the current math leads to misleading puzzles. The learning curve of GA is a smooth, the time-consuming part is mapping them back to old-fashion math and explain the differences or even seemingly contradictions. I do understand the importance to review all "established" physics, the meaning can be explained by a quote from [An Introduction to Geometric Algebra with some Preliminary Thoughts on the Geometric Meaning of Quantum Mechanics](http://www2.montgomerycollege.edu/departments/planet/planet/Numerical_Relativity/IntroGAhighschoolEdition.pdf) : 

> * Geometric Algebra provides a unified language for the whole of physics that is conceptually and
 computationally superior to alternative mathematical systems in every application domain
> * Reforming the mathematical language of physics is the single most essential step toward
 simplifying physics education at all levels from high school to graduate school

But what I was looking for, was the breadcrumb of serious adoption of GA in edge theoretical physics research and their findings.

**Comment by brombo** [comment]
On 05/09/2016 07:24 AM, Utensil Song wrote:
>
> The last paragraph of my last comment may seem a little doubtful about 
> GA. Actually, I was trying to neutralize my more enthusiastic and 
> radical view: The current math used in physics is not only inefficient 
> but also wrong. By "wrong", I mean that the inefficiency of the 
> current math leads to misleading puzzles. The learning curve of GA is 
> a smooth, the time-consuming part is mapping them back to old-fashion 
> math and explain the differences or even seemingly contradictions. I 
> do understand the importance to review all "established" physics, the 
> meaning can be explained by a quote from An Introduction to Geometric 
> Algebra with some Preliminary Thoughts on the Geometric Meaning of 
> Quantum Mechanics 
> <http://www2.montgomerycollege.edu/departments/planet/planet/Numerical_Relativity/IntroGAhighschoolEdition.pdf> 
> :
>
>       * Geometric Algebra provides a unified language for the whole of
>         physics that is conceptually and computationally superior to
>         alternative mathematical systems in every application domain
>       * Reforming the mathematical language of physics is the single
>         most essential step toward simplifying physics education at
>         all levels from high school to graduate school
>
> But what I was looking for, was the breadcrumb of serious adoption of 
> GA in edge theoretical physics research and their findings.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/14#issuecomment-217839526>
>
The version of BookGA.pdf on Google drive is the latest version.  As the 
Cliffhangers cover material on Friday evenings corrections and additions 
are suggested that I perform during the following week.

**Comment by utensil** [comment]
> The version of BookGA.pdf on Google drive is the latest version.

Sorry, I can't find your Google Drive.

> As the
> Cliffhangers cover material on Friday evenings corrections and additions
> are suggested that I perform during the following week.

I can't quite follow you on this.

**Comment by utensil** [comment]
Progress update: I'll start to work on fixing the tests in the coming week.

**Comment by utensil** [comment]
I'm currently converting test cases one by one. The assertions are usually valid, but there're edge cases with slight differences, correcting the assertions with my own eyes.

There's one problematic:

```py
# FIXME failed with value: (a.b)*c - (b.c)*a - ((a.b)*c - (b.c)*a)
assert str((a|(b^c))+(c|(a^b))+(b|(c^a))) == '0'
```

It's obvious the output is 0, but not simplified to 0. @brombo , do you know what caused this? This seems to be a problem of the implmentation, not the assertion.

**Comment by utensil** [comment]
An extra `.simplify()` turn it into 0, see https://github.com/utensil-contrib/galgebra/commit/7b9425ef3a358f1e4ccbef3092806bf8aa453729

Is this intended?

**Comment by brombo** [comment]
Simplify can be costly in time so it is not automatically applied after 
each operation.  It is always a good idea to simplify if testing an 
expression to be zero.

**Comment by utensil** [comment]
Yeah, I also thought that the reason would be for performance.

**Comment by micahscopes** [comment]
I have a glsl generator that relies on sage's Clifford Algebra tools to generate high dimensional rotation functions.  (I used to rely on sympy.galgebra, until it got spun off into this project).  Anyhow, I really would love to be able to switch back to this library so I can publish my project, but I'm using setup.py/pip for dependency management...  And pip has removed support for external dependencies.

So I'm kinda at a loss!  I don't want to use requirements.txt, cause I want to publish my library.  What's holding up this ticket.  Is there anything I can do to help?  Maybe you are waiting to do a stable release?

**Comment by utensil** [comment]
@micahscopes 

My plan was add some code to make the project pip-compatible, improve the unit tests and assist in the registering process. The first part is completed, the second part(almost completed) lead me to find a few bugs and I fixed them in my way and presented the codes to be reviewed in #20 . Then, my work on it has stopped after some [frustrating communication experience](https://github.com/brombo/galgebra/issues/20#issuecomment-229374231) and @brombo kept working on the project and the PR became obsolete. After that, my life took a dramatic turn so I haven't been using or concerning this project ever since.

Personally I can update #20 to match the status of the master branch, but the final part relies heavily on @brombo 's own willing and efforts, along with an open communication channel. The work has paused due to the lack of both.

Hope the information helps. I'm always willing to continue the work on this issue.

**Comment by utensil** [comment]
I'll close this issue as pygae/galgebra#2 is now merged.
