### ISSUE TITLE
diff not working

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#16]
From the doc:

diff(self,var)
Calculate derivative of each multivector coefficient with respect to variable var and form new multivector from coefficients.

So I try:

import ga,sympy
base=ga.Ga('b*1|2',g=[1,1])
time=sympy.symbols('t',real=True)
f=sympy.symbols('f',cls=sympy.Function)(time)
print f.diff(time)
a=f*base.I()
print a.diff(time)

D{t}f
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print a.diff(time)
  File "/home/ken/galgebra-master/galgebra/mv.py", line 1047, in diff
    if coord not in self.Ga.coords:
TypeError: argument of type 'NoneType' is not iterable

**Comment by brombo** [comment]
Have fixed and push correction to Mv.diff().  Your code also had errors 
(typos) see below -

import ga,sympy
time,x,y=sympy.symbols('t x y',real=True)

base=ga.Ga('b*1|2',g=[1,1])
basis = base.mv()
print basis
f=sympy.symbols('f',cls=sympy.Function)(time)
print f.diff(time)
a=f*base.I()
print a.diff(time)

**Comment by gcwenken** [comment]
I know, I just write something as you write in my python file, but when I copy and paste here, it replace everything between the * in base=ga.Ga('b*1|2',g=[1,1]), and  the * in a=f*base.I() into Italian font and cancel the above two *. Maybe I should add an space after *, so that the codes will not be changed.
