### ISSUE TITLE
regression about manifold and simple algebra

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#17]
First test about manifold:

import ga,sympy
t=sympy.symbols('t',real=True)
x,y,z=sympy.symbols('x,y,z',cls=sympy.Function)
curve=ga.Ga('b',coords=(t,),X=[x(t),y(t),z(t)])
print curve.mv()

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    curve=ga.Ga('b',coords=(t,),X=[x(t),y(t),z(t)])
  File "/home/ken/Downloads/galgebra-master/galgebra/ga.py", line 359, in __init__
    if self.e_sq_sgn == '+': # I**2 = 1
AttributeError: 'Ga' object has no attribute 'e_sq_sgn'

But it works on the previous galgebra version(I downloaded this March), obviously there is no definition about e_sq_sgn in file ga.py

Second test about simple algebra:
It is from test_test.py in the tests folder

import ga
(a,b,c)=ga.Ga('a b c').mv()
assert str((a|(b^c))+(c|(a^b))+(b|(c^a))) == '0'

it fail the assert, because galgebra does not simplify (a|(b^c))+(c|(a^b))+(b|(c^a)) to 0, it just output
(a.b)*c - (b.c)*a - ((a.b)*c - (b.c)*a)
Also, such case work in the March version.

**Comment by brombo** [comment]
Added input Isq to Ga.  For case of I**2 not a number indicates sign of 
I**2.  Default is Isq='-'. Would be needed for general metric as in your 
example.
Pushed changes to github.  Try now.
