### ISSUE TITLE
cannot create a basis (the old way?)

### ISSUE THREAD

**Issue by foobarz** [brombo/galgebra#2]
I have been able before to make a basis for STA like this:
(e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric='[1,-1,-1,-1]')

but now I get this error:

AttributeError                            Traceback (most recent call last)
<ipython-input-35-e9aa73f1e3d9> in <module>()
----> 1 (e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric='[1,-1,-1,-1]')

/home/devel/src/galgebra/galgebra-master/galgebra/mv.pyc in setup(basis, metric, coords, rframe, debug, curv)
   2381             MV.GA = ga.Ga(basis, g=None, coords=coords, X=curv[0], debug=debug)
   2382         else:
-> 2383             MV.GA = ga.Ga(basis, g=metric, coords=coords, X=curv[0], debug=debug)
   2384         MV.I = MV.GA.i
   2385         MV.metric = MV.GA.g

AttributeError: 'module' object has no attribute 'Ga'

I'm not too experienced with the galgebra module, but this used to work. Not sure how I should be doing it now.

**Comment by foobarz** [comment]
Well, now it seems to work after I cleared all cells and restarted the kernel. Maybe this is not an issue afterall.

**Comment by brombo** [comment]
Ipython notebook is not as thoroughly tested as simply running a python program using galgebra.  Also, I am not as familiar with the quirks of Ipython notebook.  What OS are you running under. I know you closed the issue, but it is apt to pop up again.

**Comment by brombo** [comment]
Instead of 
(e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric='[1,-1,-1,-1]')
use
(e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric=[1,-1,-1,-1])
If metric is input as list or list of lists no more quotes (not input as a string).

Please look at documentation with latest versions.

**Comment by foobarz** [comment]
I am on linux. I will be downloading and looking at the changes you have uploaded a bit later (need to sleep soon). I will try to learn from the doc how to setup correctly too. Thanks. :)
