### ISSUE TITLE
powers of multivectors

### ISSUE THREAD

**Issue by arsenovic** [brombo/galgebra#21]
would be nice if you could raise multivectors to powers, so that  

    e1**2

would work.

**Comment by arsenovic** [comment]
ok perhaps my version is old then , i get

￼
e1**2
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-102-110c7c6580b9> in <module>()
----> 1 e1**2

TypeError: unsupported operand type(s) for ** or pow(): 'Mv' and 'int'

**Comment by brombo** [comment]
Example from current version.

from sympy import symbols
from ga import Ga
from mv import com

(g3d,x,y,z) = Ga.build('x y z',g=[1,1,1])

print '\nx**4 =',x**4

A = g3d.mv('A','mv')

print '\nA =',A
print '\nA**2 =',A**2

"""
x**4 = 1

A = A + A__1*x + A__2*y + A__3*z + A__12*x^y + A__13*x^z + A__23*y^z + 
A__123*x^y^z

A**2 = A**2 + A__1**2 - A__12**2 - A__123**2 - A__13**2 + A__2**2 - 
A__23**2 + A__3**2 + (2*A*A__1 - 2*A__123*A__23)*x + (2*A*A__2 + 
2*A__123*A__13)*y + (2*A*A__3 - 2*A__12*A__123)*z + (2*A*A__12 + 
2*A__123*A__3)*x^y + (2*A*A__13 - 2*A__123*A__2)*x^z + (2*A*A__23 + 
2*A__1*A__123)*y^z + (2*A*A__123 + 2*A__1*A__23 + 2*A__12*A__3 - 
2*A__13*A__2)*x^y^z
"""

**Comment by arsenovic** [comment]
sweet, ill pull a recent copy.
