### ISSUE TITLE
does sympy.solve work ? 

### ISSUE THREAD

**Issue by arsenovic** [brombo/galgebra#24]
solve works norally

    solve(sin(theta), theta,set=True)

but  when used with a multivector ( e1 is a vector)

    solve(sin(theta)*e1, theta,set=True)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-120-67f19362cd48> in <module>()
      1 
----> 2 solve(sin(theta)*e1, theta,set=True)

/home/alex/anaconda/lib/python2.7/site-packages/sympy/solvers/solvers.pyc in solve(f, *symbols, **flags)
    677                        )
    678                       )
--> 679     f, symbols = (_sympified_list(w) for w in [f, symbols])
    680 
    681     implicit = flags.get('implicit', False)

/home/alex/anaconda/lib/python2.7/site-packages/sympy/solvers/solvers.pyc in <genexpr>((w,))
    677                        )
    678                       )
--> 679     f, symbols = (_sympified_list(w) for w in [f, symbols])
    680 
    681     implicit = flags.get('implicit', False)

/home/alex/anaconda/lib/python2.7/site-packages/sympy/solvers/solvers.pyc in _sympified_list(w)
    668 
    669     def _sympified_list(w):
--> 670         return list(map(sympify, w if iterable(w) else [w]))
    671     bare_f = not iterable(f)
    672     ordered_symbols = (symbols and

/home/alex/anaconda/lib/python2.7/site-packages/sympy/core/sympify.pyc in sympify(a, locals, convert_xor, strict, rational, evaluate)
    275         try:
    276             return type(a)([sympify(x, locals=locals, convert_xor=convert_xor,
--> 277                 rational=rational) for x in a])
    278         except TypeError:
    279             # Not all iterables are rebuildable with their type.

... last 1 frames repeated, from the frame below ...

/home/alex/anaconda/lib/python2.7/site-packages/sympy/core/sympify.pyc in sympify(a, locals, convert_xor, strict, rational, evaluate)
    275         try:
    276             return type(a)([sympify(x, locals=locals, convert_xor=convert_xor,
--> 277                 rational=rational) for x in a])
    278         except TypeError:
    279             # Not all iterables are rebuildable with their type.

RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by brombo** [comment]
Sympy solve does not work with multivectors.
