### ISSUE TITLE
modify int division in metric.py to make port to python3 easier

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#25]
Hi:

I try to modify galgebra to satisfy python3. When I use python -3 to test my program, there is a warning about  line 733:

if ((self.n*(self.n-1))/2+self.sig[1])%2 == 1:

It is clear you want floor division (the answer is an int). However, such statement in python3 will produce true division (the answer is float). So I suggest to modify such statement to:

if ((self.n*(self.n-1))//2+self.sig[1])%2 == 1:

change / into //. Such change does not do harm to python2.7 user, because python2.7 also consider // as floor division.

**Comment by brombo** [comment]
which file is it in?

**Comment by gcwenken** [comment]
file galgebra/metric.py

line 733

if ((self.n*(self.n-1))/2+self.sig[1])%2 == 1:

to

if ((self.n*(self.n-1))//2+self.sig[1])%2 == 1:

________________________________

**Comment by brombo** [comment]
Change pushed to github.
