### ISSUE TITLE
fix cyclic import in python3

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#26]
Hi:

python3 does not support cyclic import from top of module. For example in file galgebra/ga.py line 9:

import printer

file galgebra/printer line 25

import ga

That causes cyclic import. I see all the files in galgebra need the module from printer.py, but printer.py does not need the others, because there is no explicit ga., mv., lt. and metric. in printer.py. So the fix is easy, just remove line 25 to line 28 in printer.py:
25 import ga
26 import mv
27 import lt
28 import metric

**Comment by brombo** [comment]
Pushed suggested changes to github/galgebra.
