### ISSUE TITLE
error trying to get the norm() of a symbolic vector

### ISSUE THREAD

**Issue by foobarz** [brombo/galgebra#3]
I make some symbols...
(a,b,c,ta,tb,vxa,vya,vza,vxb,vyb,vzb) = symbols('a b c t_a t_b v_xa v_ya v_za v_xb v_yb v_zb')
(va,vb,uva,uvb,ha,hb,ga,gb) = symbols('v_a v_b u_va u_vb h_a h_b g_a g_b')

Set a symbolic vector to some products of symbols...
va = vxa * e1 + vya * e2 + vza * e3

Then try to see the symbolic expression of the norm...
va.norm()

But then I get this error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-ed8e3ad672bc> in <module>()
----> 1 va.norm()

/home/devel/src/galgebra/galgebra-master/galgebra/mv.pyc in norm(self, hint)
   1095                     return metric.square_root_of_expr(product.obj)
   1096                 else:
-> 1097                     return metric.square_root_of_expr(-product.obj)
   1098         else:
   1099             raise TypeError('"(' + str(product) + ')" is not a scalar in norm.')

AttributeError: 'Add' object has no attribute 'obj'

Not sure what the problem is. I have done stuff like this before and have normally seen nice symbolic LaTeX output.

**Comment by brombo** [comment]
Would you list exact code you are using?

**Comment by brombo** [comment]
Fixing problem.  Should update repository sometime today (5/20/15).

**Comment by foobarz** [comment]
I am learning and playing with STA.  Here is the code. Sorry if the paste of the notebook is hard to read...

G1,3 Space-Time Algebra
In [1]:

from sympy import *

In [2]:

from sympy.printing import *

In [3]:

from galgebra.ga import *

In [4]:

from galgebra.mv import *

In [5]:

from galgebra.lt import *

In [6]:

from galgebra.metric import *

In [7]:

from galgebra.printer import *

In [8]:

from sympy.core.cache import *

In [9]:

clear_cache()

In [10]:

init_printing()

In [11]:

Format()

Basis Vectors
In [12]:

(e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric='[1,-1,-1,-1]')

Pseudoscalars
In [13]:

I4 = symbols('I_4')

In [14]:

I4 = e0^e1^e2^e3

In [15]:

I4

Out[15]:
e0∧e1∧e2∧e3
Tests
In [16]:

(a,b,c,ta,tb,vxa,vya,vza,vxb,vyb,vzb) = symbols('a b c t_a t_b v_xa v_ya v_za v_xb v_yb v_zb')

In [17]:

(va,vb,uva,uvb,ha,hb,ga,gb) = symbols('v_a v_b u_va u_vb h_a h_b g_a g_b')

Observer a and the a-system.

a=ctae0−vtau

The velocity v must be a constant for special relativity (SR).

Observer b sees a move with velocity −v.

aa===(ae0)(e0a)(cta+vtaU)(cta−vtaU)c2t2a−v2t2a
In [18]:

va = vxa*e1 + vya*e2 + vza*e3

In [19]:

va

Out[19]:
vxae1+vyae2+vzae3
In [42]:

va.norm(hint='-')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-274ae133870b> in <module>()
----> 1 va.norm(hint='-')

/home/devel/src/galgebra/galgebra-master/galgebra/mv.pyc in norm(self, hint)
   1095                     return metric.square_root_of_expr(product.obj)
   1096                 else:
-> 1097                     return metric.square_root_of_expr(-product.obj)
   1098         else:
   1099             raise TypeError('"(' + str(product) + ')" is not a scalar in norm.')

AttributeError: 'Add' object has no attribute 'obj'

**Comment by brombo** [comment]
The was an error in function Mv.norm().  Just pushed correction to 
github repository.  If you are using Ipython notebook why not attach 
.ipynb file to email and send it to me.

**Comment by foobarz** [comment]
norm() works now, so closing... thanks a lot :)
