### ISSUE TITLE
PolynomialError trying to call exp() function to make a versor

### ISSUE THREAD

**Issue by foobarz** [brombo/galgebra#4]
I am trying to use the exp() function to make a hyperbolic versor to rotate space-time, and I get a "polynomial error" ... excuse the code itself, it is just a rough attempt to try some space-time Lorentz transformations, and it could be setup wrong!

G1,3 Space-Time Algebra
In [1]:

from sympy import *

In [2]:

from sympy.printing import *

In [3]:

from galgebra.ga import *

In [4]:

from galgebra.mv import *

In [5]:

from galgebra.lt import *

In [6]:

from galgebra.metric import *

In [7]:

from galgebra.printer import *

In [8]:

from sympy.core.cache import *

In [9]:

clear_cache()

In [10]:

init_printing()

In [11]:

Format()

Basis Vectors
In [12]:

(e0,e1,e2,e3) = MV.setup('e*0|1|2|3',metric=[1,-1,-1,-1])

Pseudoscalars
In [13]:

I4 = symbols('I_4')

In [14]:

I4 = e0^e1^e2^e3

In [15]:

I4

Out[15]:
e0∧e1∧e2∧e3
Tests
In [16]:

(a,b,c,ta,tb,vxa,vya,vza,vxb,vyb,vzb) = symbols('a b c t_a t_b v_xa v_ya v_za v_xb v_yb v_zb')

In [17]:

(va,vb,uva,uvb,ha,hb,ga,gb) = symbols('v_a v_b u_va u_vb h_a h_b g_a g_b')

Observer a and the a-system.

a=ctae0−vtau

The velocity v must be a constant for special relativity (SR).

Observer b sees a move with velocity −v.

aa===(ae0)(e0a)(cta+vtaU)(cta−vtaU)c2t2a−v2t2a
In [18]:

va = vxa*e1 + vya*e2 + vza*e3

In [19]:

va

Out[19]:
vxae1+vyae2+vzae3
In [20]:

va.norm(hint='-')

Out[20]:
∣∣v2xa+v2ya+v2za∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√
In [21]:

uva=va*Pow(sqrt(va.norm2()),-1)

In [22]:

uva

Out[22]:
vxa∣∣(vxa)2+(vya)2+(vza)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e1+vya∣∣(vxa)2+(vya)2+(vza)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e2+vza∣∣(vxa)2+(vya)2+(vza)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e3
In [23]:

a = (c*ta)*e0 + va*ta

In [24]:

a

Out[24]:
ctae0+tavxae1+tavyae2+tavzae3
In [25]:

ha = atanh(sqrt(va.norm2())*Pow(c,-1) )

In [26]:

ha

Out[26]:
atanh(1c∣∣v2xa+v2ya+v2za∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√)

Observer b and the b-system.

b=ctbe0+vtbu

Observer a sees b move with velocity v.

SR also assumes that a=b=0 at ta=tb=0.
In [27]:

vb = vxb*e1 + vyb*e2 + vzb*e3

In [28]:

uvb = vb*Pow(sqrt(vb.norm2()),-1)

In [29]:

uvb

Out[29]:
vxb∣∣(vxb)2+(vyb)2+(vzb)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e1+vyb∣∣(vxb)2+(vyb)2+(vzb)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e2+vzb∣∣(vxb)2+(vyb)2+(vzb)2∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√e3
In [30]:

b = (c*tb)*e0 + vb*tb

In [31]:

b

Out[31]:
ctbe0+tbvxbe1+tbvybe2+tbvzbe3
In [32]:

hb = atanh( sqrt(vb.norm2())*Pow(c,-1) )

In [33]:

hb

Out[33]:
atanh(1c∣∣v2xb+v2yb+v2zb∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√)
In [34]:

Pow(va.norm(),-1)

Out[34]:
1∣∣v2xa+v2ya+v2za∣∣‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√
In [35]:

(Rational(1,2)*ha*(uva^e0)).exp()

---------------------------------------------------------------------------
PolynomialError                           Traceback (most recent call last)
<ipython-input-35-d7995cf94923> in <module>()
----> 1 (Rational(1,2)*ha*(uva^e0)).exp()

/home/devel/src/galgebra/galgebra-master/galgebra/mv.pyc in exp(self, hint)
    996                     return Mv(S(1), 'scalar', ga=self.Ga)
    997             else:
--> 998                 norm = metric.square_root_of_expr(sq)
    999                 value = self.obj / norm
   1000                 if hint == '+':

/home/devel/src/galgebra/galgebra-master/galgebra/metric.pyc in square_root_of_expr(expr)
    103     else:
    104         expr = trigsimp(expr)
--> 105         (coef, pow_lst) = sqf_list(expr)
    106         if coef != S(1):
    107             if coef.is_number:

/home/devel/anaconda/lib/python2.7/site-packages/sympy/polys/polytools.pyc in sqf_list(f, *gens, **args)
   5851 
   5852     """
-> 5853     return _generic_factor_list(f, gens, args, method='sqf')
   5854 
   5855 

/home/devel/anaconda/lib/python2.7/site-packages/sympy/polys/polytools.pyc in _generic_factor_list(expr, gens, args, method)
   5625 
   5626         if fq and not opt.frac:
-> 5627             raise PolynomialError("a polynomial expected, got %s" % expr)
   5628 
   5629         _opt = opt.clone(dict(expand=True))

PolynomialError: a polynomial expected, got \frac{{\left ( v_{xa} \right )}^{2} atanh ^{2}}{4 \left\lvert{{\left ( v_{xa} \right )}^{2} + {\left ( v_{ya} \right )}^{2} + {\left ( v_{za} \right )}^{2}}\right\rvert} + \frac{{\left ( v_{ya} \right )}^{2} atanh ^{2}}{4 \left\lvert{{\left ( v_{xa} \right )}^{2} + {\left ( v_{ya} \right )}^{2} + {\left ( v_{za} \right )}^{2}}\right\rvert} + \frac{{\left ( v_{za} \right )}^{2} atanh ^{2}}{4 \left\lvert{{\left ( v_{xa} \right )}^{2} + {\left ( v_{ya} \right )}^{2} + {\left ( v_{za} \right )}^{2}}\right\rvert}

**Comment by brombo** [comment]
If you are using Ipython notebook please send attached .ipynb file.  exp 
of a multivector is not implemented.  Look at example 
galgebra-master/examples/LaTeX/physics_check_latex.py

**Comment by foobarz** [comment]
I'm continuing to have many strange problems, even with the latest galgebra-master. There seems to be many issues that result in a "ValueError" when trying to use exp() in cases similar to

exp( -Rational(1,2) * atanh(norm(v^u)*Pow(norm(v|u),-1)) * (v^u)*Pow(norm(v^u),-1) )

where this is a hyperbolic versor made from two time-like spacetime velocities v and u in the spacetime algebra (STA).

I can get this exp() to work and get a versor, but if I fool around with it and try

exp( -Rational(1,2) * N(atanh(norm(v^u)*Pow(norm(v|u),-1))) * (v^u)*Pow(norm(v^u),-1) )

to use a numerical angle, then I typically get a ValueError. Some very messy symbolic results are output and so I tried putting in numerical numbers to try to make it simpler, but it does not always work. Some symbolic expressions are large, and I am thinking that when I reduce them to scalars, I am getting significant numerical rounding errors and is making it hard for me to compare different formulas which I think should give the same results.

Anyhow, I'm not sure what the problem is exactly. I could be using it wrong. I use the software to try to test things out as I learn things. If I figure out more specific things, I can try to post the details.

**Comment by brombo** [comment]
On 05/29/2015 01:41 PM, foobarz wrote:
>
> I'm continuing to have many strange problems, even with the latest 
> galgebra-master. There seems to be many issues that result in a 
> "ValueError" when trying to use exp() in cases similar to
>
> exp( -Rational(1,2) * atanh(norm(v^u)/Pow(norm(v|u),-1)) * 
> (v^u)/Pow(norm(v^u),-1) )
>
> where this is a hyperbolic versor made from two time-like spacetime 
> velocities v and u in the spacetime algebra (STA).
>
> I can get this exp() to work and get a versor, but if I fool around 
> with it and try
>
> exp( -Rational(1,2) * N(atanh(norm(v^u)/Pow(norm(v|u),-1))) * 
> (v^u)/Pow(norm(v^u),-1) )
>
> to use a numerical angle, then I typically get a ValueError. Some very 
> messy symbolic results are output and so I tried putting in numerical 
> numbers to try to make it simpler, but it does not always work. Some 
> symbolic expressions are large, and I am thinking that when I reduce 
> them to scalars, I am getting significant numerical rounding errors 
> and is making it hard for me to compare different formulas which I 
> think should give the same results.
>
> Anyhow, I'm not sure what the problem is exactly. I could be using it 
> wrong. I use the software to try to test things out as I learn things. 
> If I figure out more specific things, I can try to post the details.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/4#issuecomment-106882880>.
>
Run the following code:

from sympy import symbols,sin,cos,atanh,Rational,Pow
from ga import Ga
from printer import Eprint

def f_uv(u,v):
     print 'Example:'
     print 'u =',u
     print 'v =',v
     print 'u|v =', u|v
     print 'u^v =', u^v
     print '(u^v).norm2() =', (u^v).norm2()
     print '(u^v).norm() =', (u^v).norm()
     return

def main():
     Eprint()
     (st4d,et,ex,ey,ez) = Ga.build('e*t|x|y|z',g=[1,-1,-1,-1])

     u = st4d.mv('u','vector')
     v = st4d.mv('v','vector')

     f_uv(u,v)
     f_uv(ex,ey)
     f_uv(et,ex)

     print 'atanh((v^u).norm(None)) =',atanh((v^u).norm(None))
     print 'Pow((v|u).norm(None),-1) =',Pow((v|u).norm(None),-1)
     print 
'Rational(1,2)*(atanh((v^u).norm(None)*Pow((v|u).norm(None),-1))*Pow((v^u).norm(None),-1))*(v^u) 
=\n', \
Rational(1,2)*(atanh((v^u).norm(None)*Pow((v|u).norm(None),-1))*Pow((v^u).norm(None),-1))*(v^u)

     return

if __name__ == "__main__":
     main()

and get the long long result:

Example:
u = u__t*e_t + u__x*e_x + u__y*e_y + u__z*e_z
v = v__t*e_t + v__x*e_x + v__y*e_y + v__z*e_z
u|v = u__t*v__t - u__x*v__x - u__y*v__y - u__z*v__z
u^v = (u__t*v__x - u__x*v__t)*e_t^e_x + (u__t*v__y - u__y*v__t)*e_t^e_y 
+ (u__t*v__z - u__z*v__t)*e_t^e_z + (u__x*v__y - u__y*v__x)*e_x^e_y + 
(u__x*v__z - u__z*v__x)*e_x^e_z + (u__y*v__z - u__z*v__y)*e_y^e_z
(u^v).norm2() = Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + u__t**2*v__z**2 
- 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z 
+ u__x**2*v__t**2 - u__x**2*v__y**2 - u__x**2*v__z**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__t**2 - 
u__y**2*v__x**2 - u__y**2*v__z**2 + 2*u__y*u__z*v__y*v__z + 
u__z**2*v__t**2 - u__z**2*v__x**2 - u__z**2*v__y**2)
(u^v).norm() = sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))
Example:
u = e_x
v = e_y
u|v = 0
u^v = e_x^e_y
(u^v).norm2() = 1
(u^v).norm() = 1
Example:
u = e_t
v = e_x
u|v = 0
u^v = e_t^e_x
(u^v).norm2() = 1
(u^v).norm() = 1
atanh((v^u).norm(None)) = atanh(sqrt(Abs(u__t**2*v__x**2 + 
u__t**2*v__y**2 + u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - 
u__x**2*v__y**2 - u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 
2*u__x*u__z*v__x*v__z + u__y**2*v__t**2 - u__y**2*v__x**2 - 
u__y**2*v__z**2 + 2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - 
u__z**2*v__x**2 - u__z**2*v__y**2)))
Pow((v|u).norm(None),-1) = 1/sqrt(Abs(u__t**2*v__t**2 - 
2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + 
u__x**2*v__x**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__y**2 + 2*u__y*u__z*v__y*v__z + u__z**2*v__z**2))
Rational(1,2)*(atanh((v^u).norm(None)*Pow((v|u).norm(None),-1))*Pow((v^u).norm(None),-1))*(v^u) 
=
(-u__t*v__x + u__x*v__t)*atanh(sqrt(Abs(u__t**2*v__x**2 + 
u__t**2*v__y**2 + u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - 
u__x**2*v__y**2 - u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 
2*u__x*u__z*v__x*v__z + u__y**2*v__t**2 - u__y**2*v__x**2 - 
u__y**2*v__z**2 + 2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - 
u__z**2*v__x**2 - u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 
2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + 
u__x**2*v__x**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__y**2 + 2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_t^e_x/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))) + (-u__t*v__y + 
u__y*v__t)*atanh(sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__x**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__y**2 + 
2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_t^e_y/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))) + (-u__t*v__z + 
u__z*v__t)*atanh(sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__x**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__y**2 + 
2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_t^e_z/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))) + (-u__x*v__y + 
u__y*v__x)*atanh(sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__x**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__y**2 + 
2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_x^e_y/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))) + (-u__x*v__z + 
u__z*v__x)*atanh(sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__x**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__y**2 + 
2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_x^e_z/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))) + (-u__y*v__z + 
u__z*v__y)*atanh(sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 + 
u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2))/sqrt(Abs(u__t**2*v__t**2 - 2*u__t*u__x*v__t*v__x - 
2*u__t*u__y*v__t*v__y - 2*u__t*u__z*v__t*v__z + u__x**2*v__x**2 + 
2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + u__y**2*v__y**2 + 
2*u__y*u__z*v__y*v__z + 
u__z**2*v__z**2)))*e_y^e_z/(2*sqrt(Abs(u__t**2*v__x**2 + u__t**2*v__y**2 
+ u__t**2*v__z**2 - 2*u__t*u__x*v__t*v__x - 2*u__t*u__y*v__t*v__y - 
2*u__t*u__z*v__t*v__z + u__x**2*v__t**2 - u__x**2*v__y**2 - 
u__x**2*v__z**2 + 2*u__x*u__y*v__x*v__y + 2*u__x*u__z*v__x*v__z + 
u__y**2*v__t**2 - u__y**2*v__x**2 - u__y**2*v__z**2 + 
2*u__y*u__z*v__y*v__z + u__z**2*v__t**2 - u__z**2*v__x**2 - 
u__z**2*v__y**2)))

You can calculate the exponential, but you do not (in the general case) 
if the square of the exponential is positive or negative. Thus the 
program does not know where to use sin and cos or sinh and cosh in the 
expansion.  If X is the exponent you can use X.exp(hint='+') or 
X.exp(hint='-') to tell the program if the symbolic X*X is >0 or <0.

**Comment by foobarz** [comment]
I think this issue may have cleared up for me. So, I close this issue.
