### ISSUE TITLE
answers from ga.Ga.mvr and ga.Ga.ReciprocalFrame are different

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#5]
I use the following code to produce reciprocal frame
import ga
base=ga.Ga('a b')
a,b=base.mv()
ar,br=base.mvr()
but ar|a does not return 1
 
Moreover, I try to output base.E() after base.mvr(), it does not output a^b. Instead, it outputs a scalar.

Later, I try to use base.ReciprocalFrame(base.mv()) to get the reciprocal frame, then the answer is correct. So why the answers from ga.Ga.mvr and ga.Ga.ReciprocalFrame are different? It seems that mvr() does not return the reciprocal frame, what does it actually do?
![reciprocal](https://cloud.githubusercontent.com/assets/12224985/13653720/f455bda8-e618-11e5-958c-087e260a1840.png)

**Comment by brombo** [comment]
mvr is also messing up base.E().  I am working to fix this.  Thank you 
for breaking the code it really helps me.

**Comment by brombo** [comment]
Pushed correction to galgebra on github.  In future if you have code in 
notebook please attach as ipynb file.

**Comment by gcwenken** [comment]
Thank you, now mvr works ok. But you seems to forget to remove line 343 in ga.py
print 'self.e =', self.e
So when I call ga.Ga, it will automatically print the pseudoscalar

**Comment by brombo** [comment]
On 03/10/2016 07:23 PM, gcwenken wrote:
>
> Thank you, now mvr works ok. But you seems to forget to remove line 
> 343 in ga.py
> print 'self.e =', self.e
> So when I call ga.Ga, it will automatically print the pseudoscalar
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/5#issuecomment-195114282>.
>
Will fix it.  What are you using GA for?

**Comment by gcwenken** [comment]
Before the fix, the following code is working:
import ga,sympy
u,v=sympy.symbols('u,v',real=True)
x,y,z=sympy.symbols('x,y,z',Function=True)
surface=ga.Ga('e1 e2',coords=(u,v),X=[x(u,v),y(u,v),z(u,v)])
print surface.mv()

But now:
It produces the following error:
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    surface=ga.Ga('e1 e2',coords=(u,v),X=[x(u,v),y(u,v),z(u,v)])
  File "/home/ken/Downloads/galgebra-master/galgebra/ga.py", line 327, in __init__
    self.build_reciprocal_basis(self.gsym)
  File "/home/ken/Downloads/galgebra-master/galgebra/ga.py", line 1386, in build_reciprocal_basis
    self.e_obj = self.e.obj
AttributeError: 'Ga' object has no attribute 'e'

Well, actually I do not quite understand the advanced properties of GA. But I find GA is very useful to deal with a lot of stuffs that can not be handled by linear algebra, say oblique coordinates in crystallography, rotation and reflection of rigid body, analytic geometry in dimension bigger than 3, definition of volume of subspace. Moreover, use it to deduce formula in electrodynamics and hydrodynamics(geometric derivative operator). Now, I am still learning field on manifold, it maybe can help me to define correct quantum potential in phase space.

**Comment by brombo** [comment]
Fixed problem with vector manifold input and pushed to github.  Try the 
following code -

import ga,sympy
coords = u,v =sympy.symbols('u,v',real=True)
#x,y,z=sympy.symbols('x,y,z',Function=True)

x = sympy.Function('x')(*coords)
y = sympy.Function('y')(*coords)
z = sympy.Function('z')(*coords)

#surface=ga.Ga('e1 e2',coords=(u,v),X=[x(u,v),y(u,v),z(u,v)])
surface=ga.Ga('e1 e2',coords=(u,v),X=[x,y,z])
print surface.g
eu,ev = surface.mv()
eur,evr = surface.mvr()
print (eu|eur).simplify()
print (eu|evr).simplify()
print (ev|eur).simplify()
print (ev|evr).simplify()

I could not get you sympy function definition to work for me.
Note that code took awhile to run on my machine (10 sec)
