### ISSUE TITLE
mv.blade_coefs() is not working

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#7]
example:
import ga,sympy
base=ga.Ga('a b')
a,b=base.mv()
m,n=sympy.symbols('m,n',real=True)
v=m*a+n*b
print v.blade_coefs([a])

output:
Traceback (most recent call last):
  File "ttry.py", line 6, in <module>
    print v.blade_coefs([a])
  File "/home/ken/galgebra-master/galgebra/mv.py", line 998, in blade_coefs
    if base in bases_lst:
NameError: global name 'bases_lst' is not defined

It seems that bases_lst is a typo, there is no definition of bases_lst in blade_coefs.

**Comment by brombo** [comment]
Fixed Mv class function blade_coefs() (actually Sylvain Meunier fixed 
it) and pushed to github/galgebra.  Test code below -


from sympy import symbols,S
from ga import Ga
from printer import Eprint, Get_Program, Print_Function

def coefs_test():
     Print_Function()

     (o3d,e1,e2,e3) = Ga.build('e_1 e_2 e_3',g=[1,1,1])
     print o3d.blades_lst
     print o3d.mv_blades_lst
     v = o3d.mv('v', 'vector')
     print v
     print v.blade_coefs([e3,e1])
     A = o3d.mv('A', 'mv')
     print A
     print A.blade_coefs([e1^e3,e3,e1^e2,e1^e2^e3])
     print A.blade_coefs()
     return

def dummy():
     return

def main():
     Get_Program()
     Eprint()
     coefs_test()
     return

if __name__ == "__main__":
     main()

Code output:

[e_1, e_2, e_3, e_1^e_2, e_1^e_3, e_2^e_3, e_1^e_2^e_3]
[e_1, e_2, e_3, e_1^e_2, e_1^e_3, e_2^e_3, e_1^e_2^e_3]
v__1*e_1 + v__2*e_2 + v__3*e_3
[v__3, v__1]
A + A__1*e_1 + A__2*e_2 + A__3*e_3 + A__12*e_1^e_2 + A__13*e_1^e_3 + 
A__23*e_2^e_3 + A__123*e_1^e_2^e_3
[A__13, A__3, A__12, A__123]
[A__1, A__2, A__3, A__12, A__13, A__23, A__123]
