### ISSUE TITLE
commutator / anticommutator operators?

### ISSUE THREAD

**Issue by rbeaster** [brombo/galgebra#8]
Are there operator symbols for _commutator_
```
 a _commutator_ b =  (1/2)*(ab - ba)
```
and _anticommutator_
```
a _anticommutator_ b = (1/2)*(ab + ba)
```
such that
```
ab = a _commutator_ b + a _anticommutator_ b
```
?

I could not find them. I suppose they require overloading a symbol/operator for them, if possible. I see that the function Com(a,b) is defined, but using that function is difficult when Com is used repeatedly in a nesting. I'm not sure what symbols are available for these.

There are only so many symbols that can be overloaded, usually. Maybe that is problem. I have not looked into how exactly to overload in python. I've only seen it in C++ before.

I think that when working with bivectors in an algebra of more than 3 dimensions, the commutator and anticommutator are products that are used often. It would be nice to have operators for them, not just functions.

**Comment by brombo** [comment]
On 10/25/2015 05:40 AM, Robert B. Easter wrote:
>
> Are there operator symbols for /commutator/
>
> |a _commutator_ b = (1/2)*(ab - ba) |
>
> and /anticommutator/
>
> |a _anticommutator_ b = (1/2)*(ab + ba) |
>
> such that
>
> |ab = a _commutator_ b + a _anticommutator_ b |
>
> ?
>
> I could not find them. I suppose they require overloading a 
> symbol/operator for them, if possible. I see that the function 
> Com(a,b) is defined, but using that function is difficult when Com is 
> used repeatedly in a nesting. I'm not sure what symbols are available 
> for these.
>
> There are only so many symbols that can be overloaded, usually. Maybe 
> that is problem. I have not looked into how exactly to overload in 
> python. I've only seen it in C++ before.
>
> I think that when working with bivectors in an algebra of more than 3 
> dimensions, the commutator and anticommutator are products that are 
> used often. It would be nice to have operators for them, not just 
> functions.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/brombo/galgebra/issues/8>.
>
Two operators that are available are << (left shift) and >> (right 
shift).  Which would you like for commutator and which for 
anti-commutator? Parenthesis would be required everywhere no matter what!

**Comment by rbeaster** [comment]
I forgot about the parenthesis problem. The operators might still be useful. Okay... how about >> for commutator (1/2)(ab-ba), and << for anticommutator (1/2)(ab+ba). This has the sense that the commutator >> looks forward going, and the anticommutator << looks to be going in the anti-direction or backward! Then,
```
ab = (a>>b)+(a<<b)=(1/2)(ab-ba)+(1/2)(ab+ba)
```
And then, doing many commutators, for some reason... (((a>>b)>>c)>>d) still looks nicer than Com(Com(Com(a,b),c),d)?!

I suppose operators <> and >< are not available. If they were, I'd say use >< for commutator (looks similar to a cross symbol), and use <> for anticommutator (looks a little similar to a dot). Anyhow, this probably can't be done, and doesn't matter, so just use >> and <<.

If this seems good, then thanks a lot, and I'll download the new changes and try them soon. If you decide it is a bad idea, then that is fine and I could try to make a custom hack if I want these overloads that much.

**Comment by brombo** [comment]
Added << and >> and pushed to github.  Added to galgebra.pdf

**Comment by rbeaster** [comment]
I just upgraded to the current master, and I tested the new operators. They work great! Thanks a lot :) I'll close this "issue" now.
