### ISSUE TITLE
ga.Ga.lt(list) does not produce desired answer

### ISSUE THREAD

**Issue by gcwenken** [brombo/galgebra#8]
From galgebra.pdf, page 59
If M is a list of lists of scalars where all lists are equal in length to the dimension of the vector space
then the linear transformation is L(ei)=M[i][j]ej

So I expect, L(e0)=M[0][0]e0+M[0][1]e1 and L(e1)=M[1][0]e0+M[1][1]e1

But the following code does not produce desired answer
import ga,sympy
base=ga.Ga('e0 e1',g=[1,1],coords=sympy.symbols('x,y',real=True))
M=[[1,2],[3,4]]
print M[0][0],M[0][1]
print M[1][0],M[1][1]
print base.lt(M)

and the output is:
1 2
3 4
Lt(e0) = e0 + 3*e1
Lt(e1) = 2*e0 + 4*e1

but the desired answer is:
Lt(e0) = e0 + 2*e1
Lt(e1) = 3*e0 + 4*e1

**Comment by brombo** [comment]
Fixed linear transformation input error and pushed changes to github.
